### PR TITLE
ci: pin yvm version used in pipeline

### PR DESCRIPTION
**Pull request by jakebolam**
Fixes ci flakes where github quota is being hit

### CODE REVIEW

**Comment by jakebolam** [comment]
@sanchitgera noticed your branch hitting this too. Mind approving?

**Comment by sanchitgera** [comment]
Why is CI relying on this script though? And if it is, wouldn't it always want to get the latest version of YVM?

**Comment by jakebolam** [comment]
It's basically dog fooding yvm.

We use yvm's previous release to setup the pipeline to build the new release of yvm.

Pinning will get us around the quota (while not ideal) i'm currently looking at other alternatives too

**Comment by jakebolam** [comment]
The dog fooding actually caught an issue: #268

**Pull request closed without merging**
