### PR TITLE
feat: fish shell compatible

### PR DESCRIPTION
**Pull request by iamogbz**
## Description

- Move `yvm` shell function definition out of interactive block
- If running as script do nothing when no arguments passed

This allows sourcing of `yvm` using `bass`

### DevQA Prep

- Have `fish` shell
  - `$ brew install fish`
- Install [`edc/bass`](https://github.com/edc/bass)
- Please `make install-watch`, this PR uses a new package

### DevQA Steps

- In fish shell create wrapper function
```fish
function yvm
    bass . $YVM_DIR/yvm.sh ';' yvm $argv
end
```
- Run `yvm use 1.13.0`
- Should work as in bash shell

### Comments:

- Stop gap solution for fish shell users until #273 is merged. See https://github.com/tophat/yvm/issues/116#issuecomment-456819295.
- Similar technique recommended for using `nvm` in `fish` shell

### CODE REVIEW

**Comment by eastenluis** [comment]
Does sourcing through bass update `$PATH` across terminals in this case?

**Comment by iamogbz** [comment]
> Does sourcing through bass update `$PATH` across terminals in this case?

@eastenluis no, i don't think so. It just does it for the context of the command being run in the example `yvm` function

**Comment by iamogbz** [comment]
@jakebolam can we get this in, currently have to revert my `yvm.sh` everytime I update self.

**Comment by iamogbz** [comment]
Closing, feel free to reopen and merge.

**Pull request closed without merging**
